### ISSUE TITLE
Counter le nombre d'index dans l'array colors

### ISSUE THREAD

**Issue by vassilidev** [web-Nuo/portfolio#1]
https://github.com/web-Nuo/portfolio/blob/d217d867129a4f3eff0294217a054a688b021ef8/app.js#L47

Pour un soucis de maintenabilité, il vaut mieux compter le nombre d'index dans l'array !

`let randomColor = colors[Math.floor(Math.random() * colors.length)];`

**Comment by vassilidev** [comment]
Ou juste généré un index aléatoire avec la length

**Comment by nuooooooooooo** [comment]
oh wow ! Merci beaucoup pour la suggestion ! J'avais pas du tout pensé à ça 😄 Je ferai un commit aujourd'hui pour corriger ça.

**Comment by nuooooooooooo** [comment]
bon au final je l'ai seulement fait deux semaines plus tard 😅 mais c'est fait ! 
Ref: f8d8cbf0b517597c3c34efa13a7b26848db1f6aa

Encore merci pour ta contribution !

**Comment by vassilidev** [comment]
Derien !
